# NumPy 기본

수치 계산의 표준 라이브러리 NumPy 의 배열(`ndarray`) 생성, 인덱싱, 브로드캐스팅, 사칙연산과 행렬곱을 짧게 훑는 입문용 노트북입니다.

## 학습 목표
- `np.array`, `np.zeros/ones/full/eye/random` 으로 배열 만들기
- `shape` 와 인덱싱(기본/팬시) 으로 원하는 원소 꺼내기
- 브로드캐스팅으로 형상이 다른 배열 연산하기
- `+ - * /` (요소별) 과 `np.dot` / `np.matmul` (행렬곱) 의 차이

## 사용 라이브러리
- `numpy`

# 넘파이 불러오기 및 넘파이 기본


In [1]:
import numpy as np

# ndarray basic
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


## 1. ndarray 기본

`np.array(...)` 로 파이썬 리스트를 NumPy 배열로 변환합니다. `shape` 는 차원을, 인덱싱은 `a[i, j]` 처럼 콤마로 구분된 정수로 합니다.

# 넘파이 기본자료구조: ndarray

### 자주 쓰는 생성 함수

| 함수 | 설명 |
|---|---|
| `np.zeros(shape)` | 0 으로 채운 배열 |
| `np.ones(shape)` | 1 로 채운 배열 |
| `np.full(shape, v)` | 임의 값 `v` 로 채움 |
| `np.eye(n)` | n×n 단위행렬 |
| `np.random.random(shape)` | 0~1 균등 난수 |
| `np.empty(shape)` | 초기화 없이 메모리만 할당 (값은 쓰레기) |

In [ ]:
# ndarray 설정

a = np.zeros((2,2))   # 모든 요소가 0인 array 만들기
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # 모든 요소가 1인 array 만들기
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # 모든 요소가 정의된 숫자로 채워진 array 만들기
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         #  2x2 단위 행렬 만들기
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # 임의의 숫자가 채워진 array 만들기
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

f = np.empty((3,3)) # garbage 숫자가 채워진 array 만들기
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.81562443 0.5325044 ]
 [0.83952282 0.97618825]]
[[4.68937941e-310 4.68937940e-310 4.68937940e-310]
 [4.68937940e-310 4.68937940e-310 4.68937940e-310]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


### 인덱싱 — 팬시 인덱싱 (Fancy Indexing)

대괄호 안에 인덱스 리스트를 직접 넣어 원하는 위치만 골라낼 수 있습니다. `a[[0,1,2], [0,1,0]]` 는 `(0,0), (1,1), (2,0)` 세 원소를 모은 1D 배열입니다.

# 인덱싱: 주어진 array에 원하는 요소를 참조하고 대체하기

In [6]:
# indexing

a = np.array([[1,2], [3, 4], [5, 6]])

# 순서에 따른 내장된 규칙에 따라 인덱싱 (고급)
aa = a[[0, 1, 2], [0, 1, 0]]
print(aa)  # Prints "[1 4 5]"
print(aa.shape)


[1 4 5]
(3,)


In [5]:

# 위 인덱싱을 직관적으로 표현
aaa = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(aaa)  # Prints "[1 4 5]"
print(aaa.shape)


[1 4 5]
(3,)


### 브로드캐스팅 (Broadcasting)

서로 다른 모양의 배열끼리 연산할 때, 작은 배열을 자동으로 “늘려서(stretch)” 큰 배열의 모양에 맞춰 주는 기능입니다. 명시적으로 반복문으로 더하지 않아도 되니 코드가 짧고 빠릅니다.

| 좌측 shape | 우측 shape | 결과 shape | 의미 |
|---|---|---|---|
| `(4,3)` | `(3,)` | `(4,3)` | 벡터를 각 **행**에 더함 |
| `(4,3)` | `(4,1)` | `(4,3)` | 열벡터를 각 **열**에 더함 |
| `(4,3)` | `(1,)` 또는 스칼라 | `(4,3)` | 모든 원소에 더함 |

In [10]:
# Broadcasting

import numpy as np

# 벡터 v 를 차원이 같은 행렬의 행 또는 열에 더해줄 수 있음

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # 브로드캐스팅 기능을 이용하여 벡터 v를 x의 각 행에 더해줌
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
vv = np.array([[1], [1], [1], [1]])

yy = x + vv
print(yy)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


# 행렬 요소간 사칙연산: +, -, x, /
# 행렬 x 벡터, 행렬 x 행렬 연산: matmul

## 4. 사칙연산과 행렬곱

NumPy 의 `+ - * /` 는 모두 **요소별(element-wise)** 연산입니다. 수학적 의미의 행렬곱은 별도로 `np.dot` / `np.matmul` 을 써야 한다는 점을 꼭 구분해 두세요.

In [ ]:
# Math
mat1 = np.ones((3,3))
print(mat1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
cnt = 1
mat2 = np.zeros((3,3))
for i in range(3):
  for j in range(3):
    mat2[i,j] = mat1[i,j]*cnt
    cnt = cnt + 1
print(mat2)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
mat3 = (mat1 + mat2) * mat2 - mat1/mat2
print(mat3)

mat3_1 = np.subtract( np.multiply( np.add(mat1, mat2), mat2), np.divide(mat1,mat2) )
print(mat3_1)

[[ 1.          5.5        11.66666667]
 [19.75       29.8        41.83333333]
 [55.85714286 71.875      89.88888889]]
[[ 1.          5.5        11.66666667]
 [19.75       29.8        41.83333333]
 [55.85714286 71.875      89.88888889]]


### 행렬 곱: `np.dot` vs `np.matmul`

행렬 사이의 진짜 곱은 `+ - * /` 가 아닌 `np.dot` 또는 `np.matmul` 을 써야 합니다. 2D × 2D 인 경우 두 함수 결과는 동일하지만, 고차원 텐서로 가면 의미가 달라집니다.

| 함수 | 비고 |
|---|---|
| `np.dot(A, B)` | 1D × 1D = 내적, 2D × 2D = 행렬곱, 고차원에서는 마지막-1 축과 마지막 축의 합 |
| `np.matmul(A, B)` | 일반 행렬곱. 고차원은 앞쪽 차원을 배치(batch)로 취급해 “마지막 두 축” 끼리 곱 (`@` 연산자와 동일) |

In [ ]:
mat4 = np.dot(mat2, mat3)
print(mat4)

[[ 208.07142857  280.725       365.        ]
 [ 437.89285714  602.25        795.16666667]
 [ 667.71428571  923.775      1225.33333333]]


In [ ]:
mat5 = np.matmul(mat2, mat3)
print(mat5)

[[ 208.07142857  280.725       365.        ]
 [ 437.89285714  602.25        795.16666667]
 [ 667.71428571  923.775      1225.33333333]]


### 행렬 × 벡터 연산

`np.dot` 과 `np.matmul` 은 (행렬, 벡터) 인 경우 동일하게 행렬-벡터 곱을 수행하여 1D 벡터를 반환합니다. 결과 길이는 행렬의 행 수와 같습니다.

In [ ]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


In [ ]:
mat6 = np.dot(mat2, vec)
print(mat6)

[14. 32. 50.]


In [ ]:
mat7 = np.matmul(mat2, vec)
print(mat7)

[14. 32. 50.]
